export const desktop = {
  brandSubtitle: 'Engineering workbench',
  nav: { home: 'Home', sessions: 'Sessions', runs: 'Runs', datasets: 'Datasets', evaluations: 'Evaluations', knowledge: 'Knowledge', settings: 'Settings' },
  groups: { workspace: 'WORKSPACE', work: 'WORK', engineering: 'ENGINEERING', context: 'CONTEXT' },
  home: {
    kicker: 'Agent Engineering Workspace', lede: 'A calm place to run, inspect, and turn Agent work into reusable cases.', newSession: 'New Session',
    workspace: 'Workspace', chooseProject: 'Choose a project', openProjectHint: 'Open a local project to give Agent real context.', local: 'Local', openProject: 'Open Project', changeProject: 'Change',
    activity: 'Activity', recentRuns: 'Recent runs', viewAll: 'View all', noRuns: 'No runs yet. Your next Agent run will appear here.',
    assets: 'Assets', workspaceAssets: 'Workspace', datasets: 'Datasets', collections: '{{count}} collections', evaluations: 'Evaluations', reviewResults: 'Review results', knowledge: 'Knowledge', browseSources: 'Browse sources',
    footer: 'Runs, traces, retrieval facts, and evaluation results stay owned by their existing modules.', timeUnavailable: 'Time unavailable', nativeAgent: 'Native Agent',
  },
  session: {
    runWork: 'Run work', newSession: 'New Session', description: 'Give one Agent a real task in a local project.', running: 'Running', completed: 'Completed', ready: 'Ready', project: 'Project', noProject: 'No project selected', chooseDirectory: 'Choose a local directory to begin.', change: 'Change', open: 'Open Project', task: 'What do you want to work on?', taskPlaceholder: 'Fix the failing evaluation test…', agent: 'Agent', loadingAgents: 'Loading agents…', selectAgent: 'Select an agent', context: 'Context', workingDirectory: 'Working directory', selectProject: 'Select a project first', run: 'Run', liveExecution: 'Live execution', working: 'Agent is working…', runComplete: 'Run complete', readyWhen: 'Ready when you are', waiting: 'Waiting to run', timelineHint: 'Your execution timeline will appear here.', output: 'Output', inspectRun: 'Inspect Run', started: 'Started', tool: 'Tool', toolCompleted: 'Tool completed', completedDetail: 'Run finished successfully', executionFailed: 'Execution failed', runtimeReady: 'Agent runtime is ready', nativeNotConfigured: 'Native Agent is not configured. Configure a model provider before starting a session.', openModelSettings: 'Open Model Settings', agentExecutionFailed: 'Agent execution failed.',
  },
  settings: {
    models: 'Settings / Models', title: 'Model settings', description: 'Configure the default model used by the Native Agent in this Desktop workspace.', defaultModel: 'Default model', defaultDescription: 'This setting applies to new Native Agent sessions. Codex uses its own configuration.', provider: 'Provider', providerHint: 'Only providers supported by the current Desktop runtime are shown.', openaiCompatible: 'OpenAI-compatible', anthropic: 'Anthropic', baseUrl: 'Base URL', baseUrlHint: 'Use an OpenAI-compatible endpoint when connecting to a compatible service.', apiKey: 'API key', apiKeyConfiguredHint: 'A key is configured. Leave this empty to keep it.', apiKeyMissingHint: 'Your key is stored in the existing local Desktop configuration.', apiKeyEnvironmentHint: 'This value is supplied by the environment and is never shown here.', configuredPlaceholder: 'Configured — enter a new key to replace it', enterKey: 'Enter API key', clearKey: 'Clear saved key', keepKey: 'Keep configured key', model: 'Model', connection: 'Connection', connectionHint: 'Test the current draft without saving it.', connected: 'Connected', notTested: 'Not tested', environmentOverride: 'Environment override', saved: 'Model settings saved. New sessions use this configuration.', testSuccess: 'Connected. The provider accepted this configuration.', loadFailed: 'Could not load model settings.', test: 'Test connection', saving: 'Saving…', save: 'Save', show: 'Show', hide: 'Hide', authFailed: 'Authentication failed. Check your API key.', endpointFailed: 'Could not connect to provider endpoint.', modelFailed: 'The configured model could not be used.',
  },
} as const;
