"""Reusable agent runtime module for AgentService."""

from .config import AgentSettings, GuardrailsSettings, MemorySettings
from .contracts import (
    AgentAction,
    AgentDecision,
    AgentErrorDetail,
    AgentMessage,
    AgentRole,
    AppliedSkillRecord,
    AgentSessionState,
    AgentTurnRequest,
    AgentTurnResult,
    AgentTurnStreamEvent,
    HandoffDecision,
    HandoffTarget,
    KnowledgeChunk,
    ToolExecutionRecord,
)
from .guardrails import (
    Guard,
    GuardAuditCallback,
    GuardContext,
    GuardPipelineResult,
    GuardResult,
    GuardVerdict,
    GuardsPipeline,
    register_guard_factory,
    register_safe_reply_factory,
)
from .guardrails.factory import build_guards_pipeline
from .guardrails.input import InputLengthGuard, PromptInjectionGuard
from .guardrails.output import ContentSafetyGuard, PiiMaskingGuard
from .guardrails.tool import ParameterGuard
from .memory import (
    ContextManager,
    ContextWindow,
    ContextWindowConfig,
    GatewaySummarizer,
    InMemorySessionStore,
    MessagePriority,
    SessionSnapshot,
)
from .mcp import (
    McpClientManager,
    McpConnectionState,
    McpRegistryBridge,
    McpServerBinding,
    McpServerConfig,
    McpToolAdapter,
    McpToolInfo,
)
from .event_bus import EventBus, EventListener
from .events import (
    AgentEndEvent,
    AgentEvent,
    AgentStartEvent,
    MessageEndEvent,
    MessageStartEvent,
    MessageUpdateEvent,
    ToolExecutionEndEvent,
    ToolExecutionStartEvent,
    ToolExecutionUpdateEvent,
    TurnEndEvent,
    TurnStartEvent,
)
from .module import AgentModule, create_agent_module, load_agent_module
from .state import AgentState
from .orchestration import (
    AgentHandoffContext,
    AgentRouter,
    ContextPasser,
    DelegateToAgentTool,
    DelegationResult,
    DirectContextPasser,
    HandoffManager,
    HandoffResolution,
    HandoffRouteTarget,
    MAX_ORCHESTRATION_DEPTH,
    SubAgentContext,
    SubAgentExecutor,
    SubTurnRunner,
    SummarizingContextPasser,
)
from .runtime import AgentRuntime, create_agent_runtime
from .skills import (
    SkillBinding,
    SkillComposer,
    SkillPromptFragment,
    SkillRegistry,
    SkillSpec,
)
from .tools import (
    ConservativeHandoffPolicy,
    DynamicToolRegistry,
    ExternalToolConfig,
    HandoffPolicy,
    HttpToolHandler,
    KnowledgeProvider,
    NullKnowledgeProvider,
    ToolBinding,
    ToolExecutionContext,
    ToolHandler,
    ToolRegistry,
    ToolResult,
    ToolSpec,
)
from .workflow import (
    FailurePolicy,
    InputRef,
    InMemoryWorkflowStateStore,
    StepDef,
    StepExecutor,
    StepResult,
    WorkflowDef,
    WorkflowEngine,
    WorkflowRequest,
    WorkflowResult,
    WorkflowStateStore,
    WorkflowStreamEvent,
)

__all__ = [
    "AgentAction",
    "AgentDecision",
    "AgentEndEvent",
    "AgentErrorDetail",
    "AgentEvent",
    "AgentHandoffContext",
    "AgentMessage",
    "AgentModule",
    "AgentRole",
    "AgentRouter",
    "AgentRuntime",
    "AgentSessionState",
    "AgentSettings",
    "AgentStartEvent",
    "AgentState",
    "AppliedSkillRecord",
    "ContextManager",
    "ContextPasser",
    "ContextWindow",
    "ContextWindowConfig",
    "AgentTurnStreamEvent",
    "AgentTurnRequest",
    "AgentTurnResult",
    # Orchestration
    "DelegateToAgentTool",
    "DelegationResult",
    "EventBus",
    "EventListener",
    "DirectContextPasser",
    "HandoffManager",
    "HandoffResolution",
    "HandoffRouteTarget",
    "HandoffTarget",
    "MAX_ORCHESTRATION_DEPTH",
    "SubAgentContext",
    "SubAgentExecutor",
    "SubTurnRunner",
    "SummarizingContextPasser",
    # Tools — dynamic system
    "ConservativeHandoffPolicy",
    "DynamicToolRegistry",
    "ExternalToolConfig",
    "GatewaySummarizer",
    "Guard",
    "GuardAuditCallback",
    "GuardContext",
    "GuardPipelineResult",
    "GuardResult",
    "GuardVerdict",
    "GuardrailsSettings",
    "GuardsPipeline",
    "HandoffDecision",
    "HandoffPolicy",
    "HttpToolHandler",
    "InMemorySessionStore",
    "InputLengthGuard",
    "KnowledgeChunk",
    "KnowledgeProvider",
    "MemorySettings",
    "McpClientManager",
    "McpConnectionState",
    "McpRegistryBridge",
    "McpServerBinding",
    "McpServerConfig",
    "McpToolAdapter",
    "McpToolInfo",
    "MessageEndEvent",
    "MessagePriority",
    "MessageStartEvent",
    "MessageUpdateEvent",
    "NullKnowledgeProvider",
    "ContentSafetyGuard",
    "ParameterGuard",
    "PiiMaskingGuard",
    "PromptInjectionGuard",
    "SessionSnapshot",
    "SkillBinding",
    "SkillComposer",
    "SkillPromptFragment",
    "SkillRegistry",
    "SkillSpec",
    "ToolExecutionEndEvent",
    "ToolExecutionStartEvent",
    "ToolExecutionUpdateEvent",
    "ToolBinding",
    "ToolExecutionContext",
    "ToolExecutionRecord",
    "ToolHandler",
    "ToolRegistry",
    "ToolResult",
    "TurnEndEvent",
    "TurnStartEvent",
    "ToolSpec",
    "create_agent_module",
    "create_agent_runtime",
    "load_agent_module",
    "register_guard_factory",
    "register_safe_reply_factory",
    # Workflow
    "FailurePolicy",
    "InputRef",
    "InMemoryWorkflowStateStore",
    "StepDef",
    "StepExecutor",
    "StepResult",
    "WorkflowDef",
    "WorkflowEngine",
    "WorkflowRequest",
    "WorkflowResult",
    "WorkflowStateStore",
    "WorkflowStreamEvent",
]
