from typing import Any, AsyncIterator, Mapping, Protocol

class RunExecutor(Protocol):
    async def execute(self, *, input: Any, target: Any, metadata: Mapping[str, Any] | None = None) -> Any: ...
    def stream(self, *, input: Any, target: Any, metadata: Mapping[str, Any] | None = None) -> AsyncIterator[Any]: ...

class RunReader(Protocol):
    async def get_run(self, run_id: str) -> Any | None: ...
